@hostname=http://localhost:2000/api/todo

GET {{hostname}}
###
GET {{hostname}}/task


### Tasklist
###    Get Tasklists by UserID
GET {{hostname}}/tasklist&userid=1

###	   Edit Tasklist by ID
###	   Delete Tasklist by ID
###	   Create Tasklist by UserID
### Task
###	   Get Tasks by TasklistID
###	   Get Tasks by UserID
###	   Create Task by TasklistID
###	   Edit Task by ID
###	   Delete Task by ID
### Tag
###	   Get Tags by UserID
###	   Create Tag by UserID
###	   Edit Tag by ID
###	   Delete Tag by ID
### User
###	   Get User by ID
###	   Create User