@hostname=http://localhost:2000/api
@taskHostname=http://localhost:2000/api/task
@tasklistHostname=http://localhost:2000/api/tasklist
@tagHostname=http://localhost:2000/api/tag
@userHostname=http://localhost:2000/api/user
@eventHostname=http://localhost:2000/api/event


#Tasklist
###    Get Tasklists by UserID
GET {{tasklistHostname}}/1
###	   Edit Tasklist by ID
PUT {{tasklistHostname}}/1
###	   Delete Tasklist by ID
DELETE {{tasklistHostname}}/1
###	   Create Tasklist by UserID
POST {{tasklistHostname}}/1
Content-Type: application/json

{
    "title": "MatheHUE",
    "description": "Bsp 1-5"
}

### Task
###	   Get Tasks by TasklistID
###	   Get Tasks by UserID
###	   Create Task by TasklistID
###	   Edit Task by ID
###	   Delete Task by ID
### Tag
###	   Get Tags by UserID
###	   Create Tag by UserID
###	   Edit Tag by ID
###	   Delete Tag by ID
### User
###	   Get User by ID
###	   Create User