@hostname=http://localhost:2000/api

POST {{hostname}}/task
Content-Type: application/json

{
  "text": "minecraft super",
  "priority": 1
}

###
GET {{hostname}}/task

###
GET {{hostname}}

###
GET {{hostname}}/create-tables

###
POST localhost:2000
Content-Type: application/json

{
  "title": "My Task",
  "dueDate": "2024-ksdjfkasjf3",
  "description": "This is my Task",
  "priority": 1,
  "tasklistID": 1,
  "userID": 2
}
###

GET localhost:2000/emil
Content-Type: application/json

{
  "dueDate": "2024-02-14T10:10:13"
}

