@hostname=http://localhost:2000/api

POST {{hostname}}/task
Content-Type: application/json

{
  "text": "minecraft super",
  "priority": 1
}

###
GET {{hostname}}/task

###
GET {{hostname}}

###
GET {{hostname}}/create-tables

###
GET {{hostname}}/test/2

###
POST http://localhost:2000/api/login
Content-Type: application/json

{
  "email": "abc123",
  "password": "xyz"
}