@hostname=http://localhost:2000/api
@taskHostname=http://localhost:2000/api/task
@tasklistHostname=http://localhost:2000/api/tasklist
@tagHostname=http://localhost:2000/api/tag
@userHostname=http://localhost:2000/api/user
@eventHostname=http://localhost:2000/api/event



#Tasklist
###    Get Tasklists by UserID
GET {{tasklistHostname}}/luca.stinkt@hodenkobold.com
###	   Edit Tasklist by ID
PUT {{tasklistHostname}}/test24@gmx.at/3
Content-Type: application/json

{
    "title": "Hausaufgaben",
    "description": "Hier sind alle Hausaufgaben drin"
}
###	   Delete Tasklist by ID
DELETE {{tasklistHostname}}/15
###	   Create Tasklist by UserID
POST {{tasklistHostname}}/luca.stinkt@hodenkobold.com
Content-Type: application/json

{
    "title": "MatheHUE",
    "description": "Bsp 1-5"
}



###	   Get Tasks by TasklistID
GET {{taskHostname}}/tasklistID/1
###	   Get Tasks by UserID
GET {{taskHostname}}/userID/1
###	   Create Task by TasklistID
POST {{taskHostname}}/1
Content-Type: application/json

{
    "title": "MatheHUE",
    "description": "Bsp 1-5"
}
###	   Edit Task by ID
PUT {{taskHostname}}/4
Content-Type: application/json

{
    "title": "DeutschHUE",
    "description": "Buch Seite 126",
    "dueDate": "09.04.2025"
}
###	   Delete Task by ID
DELETE {{taskHostname}}/12




###	   Get Tags by UserID
GET {{tagHostname}}/lucahaas07@gmx.at
###	   Create Tag by UserID
POST {{tagHostname}}/lucahaas07@gmx.at/testing
###	   Edit Tag by ID
PUT {{tagHostname}}/1/a1
###	   Delete Tag by ID
DELETE {{tagHostname}}/3




###	   Get User by ID
GET {{userHostname}}/lucahaas07@gmx.at
###	   Create User
POST {{userHostname}}/philip.istDerBeste@geheim123.at
Content-Type: application/json

{
    "username": "pipostesting",
    "password": "geheim123"
}
###	   Edit User by ID
PUT {{userHostname}}/luca.stinkt@hodenkobold.com
Content-Type: application/json

{
    "username": "lucahaas07",
    "password": "geheim123"
}
###	   Delete User by ID
DELETE {{userHostname}}/philip.istDerBeste@geheim123.at